[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "14"

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  budgetPath = "lighthouse-budget.json"
